name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

env:
  JULIA_PKG_SERVER: https://internal.juliahub.com/

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}
      - uses: PumasAI/add-private-registry@main
        with:
          juliahub_token_encoded: ${{ secrets.JULIAHUB_TOKEN_ENCODED }}
          private_registry_name: JuliaSimRegistry
          private_registry_uuid: 309a7822-a73e-4490-9504-7d1983f27685
      - run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev xsettingsd x11-xserver-utils
      - name: Install dependencies
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs -e 'using Pkg;
                                      Pkg.setprotocol!(; domain = "github.com", protocol = "ssh"); 
                                      Pkg.add(PackageSpec(name = "JuliaSimCompiler", url = "https://github.com/JuliaComputing/JuliaSimCompiler.jl", rev = "master"));
                                      Pkg.develop(PackageSpec(path=pwd()));
                                      Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
