name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

env:
  JULIA_PKG_SERVER: https://internal.juliahub.com/

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: PumasAI/add-private-registry@main
        with:
          juliahub_token_encoded: ${{ secrets.JULIAHUB_TOKEN_ENCODED }}
          private_registry_name: JuliaSimRegistry
          private_registry_uuid: 309a7822-a73e-4490-9504-7d1983f27685
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.add(name="Documenter", rev="master"); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
